"""
attack_library.py — Unified Attack Scorer and Compiler
=========================================================
Aggregates novel attacks generated by CGAN, and sophisticated 
reconstructions from VAE and LSTM-AE, into a unified scored library.
"""

import os
import sys
import numpy as np
import pandas as pd
import torch
from sklearn.cluster import KMeans
import joblib
import networkx as nx
from tqdm import tqdm

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from config import SENSOR_NAMES, WINDOW_SIZE, DEVICE, MODELS_SAVE_DIR
from data.data_loader import get_data
from data.sequence_builder import create_sequences, get_flat_sequences
from models.vae import VAE
from models.lstm_ae import LSTMAE

_HR = "=" * 65

def get_vae_attacks(X_attack, n=500):
    """
    Extract smoothed adversarial-like attacks reconstructed by the VAE.
    """
    model_path = os.path.join(MODELS_SAVE_DIR, "vae_best.pth")
    if not os.path.exists(model_path):
        return [], []
        
    flat_seqs = get_flat_sequences(X_attack, WINDOW_SIZE)
    model = VAE(input_dim=flat_seqs.shape[1], latent_dim=16).to(DEVICE)
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))
    model.eval()
    
    # Subsample to save memory/time
    idx = np.random.choice(len(flat_seqs), min(n, len(flat_seqs)), replace=False)
    sample_tensor = torch.tensor(flat_seqs[idx], dtype=torch.float32).to(DEVICE)
    
    with torch.no_grad():
        recons, _, _ = model(sample_tensor)
        recons = recons.cpu().numpy()
        
    # Reshape back to (N, 60, 51) and take the last timestep as the 'attack' state
    recons_3d = recons.reshape(-1, WINDOW_SIZE, 51)
    attacks_1d = recons_3d[:, -1, :]
    
    return attacks_1d.tolist(), ["VAE"] * len(attacks_1d)

def get_lstm_attacks(X_attack, n=500):
    """
    Extract smoothed sequential attacks reconstructed by the LSTM-AE.
    """
    model_path = os.path.join(MODELS_SAVE_DIR, "lstm_ae_best.pth")
    if not os.path.exists(model_path):
        return [], []
        
    seqs = create_sequences(X_attack, WINDOW_SIZE)
    model = LSTMAE(input_dim=51, hidden_dim=128, bottleneck_dim=64).to(DEVICE)
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))
    model.eval()
    
    idx = np.random.choice(len(seqs), min(n, len(seqs)), replace=False)
    sample_tensor = torch.tensor(seqs[idx], dtype=torch.float32).to(DEVICE)
    
    with torch.no_grad():
        recons = model(sample_tensor).cpu().numpy()
        
    # Take the last timestep
    attacks_1d = recons[:, -1, :]
    return attacks_1d.tolist(), ["LSTM"] * len(attacks_1d)

def get_cgan_attacks():
    """
    Load all synthetic attacks generated by the Conditional GAN.
    """
    attacks = []
    sources = []
    stages = []
    
    for i in range(1, 7):
        stage = f"P{i}"
        file_path = os.path.join(MODELS_SAVE_DIR, f"generated_attacks_{stage}.npy")
        if os.path.exists(file_path):
            arr = np.load(file_path)
            attacks.extend(arr.tolist())
            sources.extend([f"CGAN_{stage}"] * len(arr))
            stages.extend([stage] * len(arr))
            
    return attacks, sources, stages

def evaluate_stealth(attacks_np, vae_model):
    """
    Computes VAE anomaly score for 1D attacks by repeating them into windows.
    Stealth = 1 - (Score / MaxScore)
    """
    # Create static windows for each attack: [attack, attack, ... 60 times]
    # shape: (N, 60, 51)
    windows = np.repeat(attacks_np[:, np.newaxis, :], WINDOW_SIZE, axis=1)
    flat_windows = windows.reshape(len(attacks_np), -1)
    
    tensor_windows = torch.tensor(flat_windows, dtype=torch.float32).to(DEVICE)
    
    # Compute scores in batches to avoid OOM
    batch_size = 256
    scores = []
    with torch.no_grad():
        for i in range(0, len(tensor_windows), batch_size):
            batch = tensor_windows[i:i+batch_size]
            s = vae_model.anomaly_score(batch).cpu().numpy()
            scores.extend(s)
            
    scores = np.array(scores)
    max_score = np.max(scores) if len(scores) > 0 and np.max(scores) > 0 else 1.0
    
    stealth = 1.0 - (scores / max_score)
    return np.clip(stealth, 0.0, 1.0)

def main():
    print(f"\n{_HR}")
    print("  1 / 4 — COMPILING ATTACK LIBRARY")
    print(_HR)
    
    X_normal, X_attack, _, _, _, _, _ = get_data()
    
    # 1. Gather all attacks
    attacks_vae, sources_vae = get_vae_attacks(X_attack, n=500)
    attacks_lstm, sources_lstm = get_lstm_attacks(X_attack, n=500)
    attacks_cgan, sources_cgan, stages_cgan = get_cgan_attacks()
    
    all_attacks = attacks_vae + attacks_lstm + attacks_cgan
    all_sources = sources_vae + sources_lstm + sources_cgan
    
    if not all_attacks:
        print("  ❌ No attacks found! Run specific model scripts first.")
        return
        
    all_attacks_np = np.array(all_attacks)
    print(f"  Aggregated {len(all_attacks_np)} total operational attacks.")
    print(f"    - VAE sourced   : {len(attacks_vae)}")
    print(f"    - LSTM sourced  : {len(attacks_lstm)}")
    print(f"    - CGAN sourced  : {len(attacks_cgan)}")
    
    print(f"\n{_HR}")
    print("  2 / 4 — COMPUTING SEVERITY & CASCADE")
    print(_HR)
    
    # Reference baselines
    normal_mean = np.mean(X_normal, axis=0)
    normal_std = np.std(X_normal, axis=0) + 1e-6
    
    # Try loading NetworkX graph, if not build a correlation-based one
    graph_path = os.path.join(os.path.dirname(__file__), "eda_outputs", "sensor_graph.pkl")
    if os.path.exists(graph_path):
        G = joblib.load(graph_path)
    else:
        # Fallback: create random scale-free structure mapped to sensors for dummy data
        G = nx.barabasi_albert_graph(51, 3)
        mapping = {i: name for i, name in enumerate(SENSOR_NAMES)}
        G = nx.relabel_nodes(G, mapping)
        
    severity_scores = []
    cascade_scores = []
    
    for attack in tqdm(all_attacks_np, desc="  Scoring Severities", leave=False):
        # Identify affected sensors (> 2 standard deviations away)
        deviation = np.abs(attack - normal_mean) / normal_std
        affected = deviation > 2.0
        
        if not np.any(affected):
            severity_scores.append(0.0)
            cascade_scores.append(0.0)
            continue
            
        # Severity = mean deviation of affected sensors
        sev = np.mean(deviation[affected])
        sev = np.clip(sev / 10.0, 0.0, 1.0) # normalize logic (e.g., 10 std dev maps to 1.0)
        severity_scores.append(sev)
        
        # Cascade = number of connected sensors / 51
        affected_names = [name for i, name in enumerate(SENSOR_NAMES) if affected[i]]
        connected = set()
        for node in affected_names:
            if node in G:
                connected.update(G.neighbors(node))
        casc = len(connected) / len(SENSOR_NAMES)
        cascade_scores.append(np.clip(casc, 0.0, 1.0))
        
    print(f"\n{_HR}")
    print("  3 / 4 — COMPUTING STEALTH & BLINDSPOT")
    print(_HR)
    
    # Load VAE to evaluate stealth
    vae_path = os.path.join(MODELS_SAVE_DIR, "vae_best.pth")
    vae_model = VAE(input_dim=3060, latent_dim=16).to(DEVICE)
    vae_model.load_state_dict(torch.load(vae_path, map_location=DEVICE))
    vae_model.eval()
    
    stealth_scores = evaluate_stealth(all_attacks_np, vae_model)
    
    # Compute unified blindspot
    severity_scores = np.array(severity_scores)
    cascade_scores = np.array(cascade_scores)
    
    blindspot_scores = (0.4 * stealth_scores) + (0.35 * severity_scores) + (0.25 * cascade_scores)
    blindspot_scores = blindspot_scores * 10.0  # Scale 0-10
    
    print(f"\n{_HR}")
    print("  4 / 4 — PROFILING CLUSTERS & EXPORTING")
    print(_HR)
    
    # K-Means clustering for Attack Type mapping
    kmeans = KMeans(n_clusters=4, random_state=42)
    clusters = kmeans.fit_predict(all_attacks_np)
    
    # Map cluster functions
    cluster_stats = []
    for c in range(4):
        idx = (clusters == c)
        c_stealth = np.mean(stealth_scores[idx])
        c_cascade = np.mean(cascade_scores[idx])
        
        # Distance to normal
        dist_normal = np.linalg.norm(np.mean(all_attacks_np[idx], axis=0) - normal_mean)
        cluster_stats.append({'id': c, 'stealth': c_stealth, 'cascade': c_cascade, 'dist': dist_normal})
        
    sorted_by_stealth = sorted(cluster_stats, key=lambda x: x['stealth'], reverse=True)
    sorted_by_cascade = sorted(cluster_stats, key=lambda x: x['cascade'], reverse=True)
    sorted_by_dist = sorted(cluster_stats, key=lambda x: x['dist'])
    
    labels = {}
    assigned = set()
    
    # 1. Highest stealth -> Silent Drift
    st_id = sorted_by_stealth[0]['id']
    labels[st_id] = "Silent Drift"
    assigned.add(st_id)
    
    # 2. Highest cascade -> Cascade Bomb
    for stat in sorted_by_cascade:
        if stat['id'] not in assigned:
            labels[stat['id']] = "Cascade Bomb"
            assigned.add(stat['id'])
            break
            
    # 3. Most similar to normal -> Ghost Signal
    for stat in sorted_by_dist:
        if stat['id'] not in assigned:
            labels[stat['id']] = "Ghost Signal"
            assigned.add(stat['id'])
            break
            
    # 4. Remaining -> Blind Spot Probe
    rem_id = list(set([0, 1, 2, 3]) - assigned)[0]
    labels[rem_id] = "Blind Spot Probe"
    
    attack_types = [labels[c] for c in clusters]
    
    # Extract stages for VAE/LSTM based on the max changed sensor (approximation)
    from models.cgan import STAGE_SENSOR_MAP
    final_stages = []
    for i, src in enumerate(all_sources):
        if src.startswith("CGAN_"):
            final_stages.append(src.split("_")[1])
        else:
            # Map based on most extreme deviation
            att = all_attacks_np[i]
            dev = np.abs(att - normal_mean) / normal_std
            max_sensor = SENSOR_NAMES[np.argmax(dev)]
            found_stage = "Unknown"
            for st, sensors in STAGE_SENSOR_MAP.items():
                if max_sensor in sensors:
                    found_stage = st
                    break
            final_stages.append(found_stage)
            
    # Build DataFrame
    df = pd.DataFrame({
        'attack_id': [f"atk_{i+1:05d}" for i in range(len(all_attacks))],
        'source': all_sources,
        'target_stage': final_stages,
        'stealth_score': stealth_scores,
        'severity_score': severity_scores,
        'cascade_potential': cascade_scores,
        'blindspot_score': blindspot_scores,
        'attack_type': attack_types,
        'sensor_values': all_attacks
    })
    
    # Save files
    os.makedirs(MODELS_SAVE_DIR, exist_ok=True)
    df.to_csv(os.path.join(MODELS_SAVE_DIR, "attack_library.csv"), index=False)
    
    top_50 = df.sort_values(by='blindspot_score', ascending=False).head(50)
    top_50.to_csv(os.path.join(MODELS_SAVE_DIR, "top_attacks.csv"), index=False)
    
    # Per-Sensor Blindspot: Compute mean blindspot of attacks that heavily affect a sensor
    sensor_vulnerabilities = {}
    for i, name in enumerate(SENSOR_NAMES):
        mask = np.abs(all_attacks_np[:, i] - normal_mean[i]) / normal_std[i] > 2.0
        if np.any(mask):
            sensor_vulnerabilities[name] = np.mean(blindspot_scores[mask])
        else:
            sensor_vulnerabilities[name] = 0.0
            
    vul_df = pd.DataFrame(list(sensor_vulnerabilities.items()), columns=['sensor', 'vuln_score'])
    vul_df = vul_df.sort_values(by='vuln_score', ascending=False)
    vul_df.to_csv(os.path.join(MODELS_SAVE_DIR, "sensor_blindspot_scores.csv"), index=False)
    
    # Summary
    print(f"\n✨ ATTACK LIBRARY HIGHLIGHTS ✨")
    print(f"Total Attacks: {len(df)}")
    print("\n[ Distribution by Source ]")
    print(df['source'].value_counts().to_string())
    print("\n[ Distribution by Attack Type ]")
    print(df['attack_type'].value_counts().to_string())
    print("\n[ Distribution by Target Stage ]")
    print(df['target_stage'].value_counts().to_string())
    print("\n[ Top 10 Most Dangerous Attacks ]")
    print(top_50[['attack_id', 'source', 'attack_type', 'blindspot_score', 'target_stage']].head(10).to_string(index=False))
    print(f"\n[ Most Vulnerable Sensor Overall ]: {vul_df.iloc[0]['sensor']} (Score: {vul_df.iloc[0]['vuln_score']:.2f})")
    print(f"\n{_HR}")
    print("✅ Library Compilation Finished.")
    print(_HR)

if __name__ == "__main__":
    main()
